"""Read-only API for documentation generated by the agent workflow."""

import base64
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException, Query, Response, status
from pydantic import BaseModel

from app.core.config import settings

router = APIRouter()

# The whole-repo Coordinator pipeline (DocumentationAgent) writes exactly
# these top-level files per repository. Anything else under generated_docs/
# is a per-file, on-demand document written by FileDocumentationService
# (see services/file_doc_service.py) and belongs on the /file-docs page's
# History section instead of the main Documentation dashboard.
_STANDARD_DOC_NAMES = {
    "README.md",
    "ARCHITECTURE.md",
    "WORKFLOW.md",
    "CHANGELOG.md",
    "SECURITY.md",
    "REPORTS.md",
}


class GeneratedDocumentSummary(BaseModel):
    """Metadata displayed in the frontend documentation dashboard."""

    id: str
    repo_id: str
    title: str
    source_path: str
    status: str = "pending_review"
    created_at: str
    has_changes: bool = False


class GeneratedDocument(GeneratedDocumentSummary):
    """A generated Markdown document and its display metadata."""

    content: str
    previous_content: Optional[str] = None


class ApproveDocumentRequest(BaseModel):
    id: str


class ReviseDocumentRequest(BaseModel):
    id: str
    comment: str


class SaveDocumentRequest(BaseModel):
    id: str
    content: str



def _documents_root() -> Path:
    return settings.generated_docs_path_dir.resolve()


def _document_id(relative_path: Path) -> str:
    encoded = base64.urlsafe_b64encode(relative_path.as_posix().encode("utf-8"))
    return encoded.decode("ascii").rstrip("=")


def _relative_path(document_id: str) -> Path:
    try:
        padded = document_id + "=" * (-len(document_id) % 4)
        decoded = base64.urlsafe_b64decode(padded.encode("ascii")).decode("utf-8")
    except (UnicodeDecodeError, ValueError) as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found") from exc

    path = Path(decoded)
    if path.is_absolute() or ".." in path.parts or path.suffix.lower() != ".md":
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")
    return path


def _sidecar_path(doc_path: Path) -> Path:
    """Return the .prev.md sidecar path for a given .md document."""
    return doc_path.with_suffix(".prev.md")


def _is_standard_doc(relative_path: Path) -> bool:
    """True for the 6 whole-repo docs (repo_slug/<name>.md), false for anything
    written by the on-demand single-file documentation feature (which mirrors
    source paths, e.g. repo_slug/src/utils/helper.py.md)."""
    return len(relative_path.parts) == 2 and relative_path.name in _STANDARD_DOC_NAMES


def _summary(path: Path, root: Path) -> GeneratedDocumentSummary:
    relative_path = path.relative_to(root)
    stat = path.stat()
    repo_id = relative_path.parts[0] if relative_path.parts else "unknown"
    title = relative_path.with_suffix("").as_posix()

    sidecar = _sidecar_path(path)

    return GeneratedDocumentSummary(
        id=_document_id(relative_path),
        repo_id=repo_id,
        title=title,
        source_path=relative_path.as_posix(),
        created_at=datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(),
        has_changes=sidecar.is_file(),
    )


@router.get("/repos", response_model=list[str])
async def list_repos() -> list[str]:
    """Return the list of repository names that have generated documentation.

    Folder names under generated_docs/ use underscores to separate the owner
    from the repo name (e.g. ``Owner_repo-name``).  We convert only the *first*
    underscore back to a slash so that names like ``my-org_my-repo`` become
    ``my-org/my-repo``.
    """
    root = _documents_root()
    if not root.exists():
        return []

    repos = []
    for entry in sorted(root.iterdir()):
        if entry.is_dir():
            # Convert "Owner_repo-name" → "Owner/repo-name" (first underscore only)
            repos.append(entry.name.replace("_", "/", 1))

    return repos


@router.get("", response_model=list[GeneratedDocumentSummary])
async def list_generated_documents() -> list[GeneratedDocumentSummary]:
    """List every Markdown document written by the Sync Agent."""
    root = _documents_root()
    if not root.exists():
        return []

    documents = [
        _summary(path, root)
        for path in root.rglob("*.md")
        if path.is_file()
        and not path.name.endswith(".prev.md")
        and _is_standard_doc(path.relative_to(root))
    ]
    return sorted(documents, key=lambda document: document.created_at, reverse=True)


@router.get("/content", response_model=GeneratedDocument)
async def get_generated_document(
    document_id: str = Query(..., alias="id"),
) -> GeneratedDocument:
    """Return one generated Markdown document by its opaque API identifier.

    Also returns ``previous_content`` (the content before the last update)
    when a ``.prev.md`` sidecar exists alongside the main file, enabling the
    frontend diff / change-highlighting view.
    """
    root = _documents_root()
    relative_path = _relative_path(document_id)
    document_path = (root / relative_path).resolve()

    if root not in document_path.parents or not document_path.is_file():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    try:
        content = document_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Generated document could not be read",
        ) from exc

    # Read the sidecar (.prev.md) if it exists — this is the previous version.
    previous_content: Optional[str] = None
    sidecar = _sidecar_path(document_path)
    if sidecar.is_file():
        try:
            previous_content = sidecar.read_text(encoding="utf-8")
        except OSError:
            previous_content = None  # Sidecar unreadable — degrade gracefully

    summary = _summary(document_path, root)
    return GeneratedDocument(
        **summary.model_dump(),
        content=content,
        previous_content=previous_content,
    )


@router.get("/serve/{repo_slug}/{filename:path}")
async def serve_raw_document(repo_slug: str, filename: str) -> Response:
    """Serve a generated Markdown file as plain text.

    This endpoint makes the generated documentation accessible via a public URL
    (e.g. through ngrok) so that GitBook can import the content using its
    ``POST /spaces/{spaceId}/import`` endpoint which fetches from a URL.

    ``filename`` may contain subdirectories — per-file, on-demand docs
    (see services/file_doc_service.py) mirror their source path, e.g.
    ``app/api/webhook.py.md`` — so this accepts a full path segment, not just
    a single path component.

    Example::

        GET /api/documents/serve/Karthik7939_Mindstride-test-repo-v1/README.md
        GET /api/documents/serve/Karthik7939_Mindstride-test-repo-v1/app/api/webhook.py.md

    Args:
        repo_slug: The folder name under generated_docs/ (underscored form).
        filename: The markdown file's path relative to the repo's doc folder.
    """
    root = _documents_root()

    # Sanitise inputs — no path traversal
    if "/" in repo_slug or ".." in repo_slug or ".." in Path(filename).parts:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid path")
    if not filename.lower().endswith(".md"):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Only .md files are served")

    doc_path = (root / repo_slug / filename).resolve()

    # Security: ensure the resolved path stays inside generated_docs/
    if root not in doc_path.parents or not doc_path.is_file():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    try:
        content = doc_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not read document",
        ) from exc

    return Response(
        content=content,
        media_type="text/plain; charset=utf-8",
        headers={"Access-Control-Allow-Origin": "*"},
    )


@router.post("/approve")
async def approve_document(body: ApproveDocumentRequest):
    """Approve a document and delete its .prev.md sidecar file so diffs are cleared."""
    root = _documents_root()
    relative_path = _relative_path(body.id)
    doc_path = (root / relative_path).resolve()

    if root not in doc_path.parents or not doc_path.is_file():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    sidecar = _sidecar_path(doc_path)
    if sidecar.is_file():
        try:
            sidecar.unlink()
        except OSError as exc:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to remove previous version sidecar",
            ) from exc

    return {"success": True, "message": "Document approved and diff cleared."}


@router.post("/revise", response_model=GeneratedDocument)
async def revise_document(body: ReviseDocumentRequest) -> GeneratedDocument:
    """Trigger LLMService/RevisionAgent to revise a document based on user feedback."""
    from services.llm_service import LLMService

    root = _documents_root()
    relative_path = _relative_path(body.id)
    doc_path = (root / relative_path).resolve()

    if root not in doc_path.parents or not doc_path.is_file():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    try:
        current_content = doc_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not read current document content",
        ) from exc

    # Backup current content as .prev.md sidecar for diff comparison
    sidecar = _sidecar_path(doc_path)
    try:
        sidecar.write_text(current_content, encoding="utf-8")
    except OSError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not create sidecar for previous version",
        ) from exc

    # Trigger LLM revision
    llm = LLMService()
    prompt = f"""You are an expert technical documentation revision agent.
The user requested the following specific changes for the document '{doc_path.name}':

USER CHANGE REQUEST / FEEDBACK:
{body.comment}

CURRENT DOCUMENTATION CONTENT:
{current_content}

Instructions:
1. Carefully modify the documentation to incorporate the user's requested changes.
2. Keep the structure clean, accurate, and properly formatted in Markdown.
3. Output ONLY the updated Markdown content. Do not include introductory conversational text or markdown code fence blocks wrapping the document.
"""

    try:
        revised_content = llm.generate(prompt)

        # Clean markdown code fences wrapping the entire output if present
        cleaned = revised_content.strip()
        if cleaned.startswith("```markdown"):
            cleaned = cleaned[11:]
        elif cleaned.startswith("```"):
            cleaned = cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
        revised_content = cleaned.strip()

        doc_path.write_text(revised_content, encoding="utf-8")
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Agent revision failed: {str(exc)}",
        ) from exc

    summary = _summary(doc_path, root)
    return GeneratedDocument(
        **summary.model_dump(),
        content=revised_content,
        previous_content=current_content,
    )


@router.post("/save", response_model=GeneratedDocument)
async def save_document(body: SaveDocumentRequest) -> GeneratedDocument:
    """Save manual edits made to a Markdown document by the user."""
    root = _documents_root()
    relative_path = _relative_path(body.id)
    doc_path = (root / relative_path).resolve()

    if root not in doc_path.parents or not doc_path.is_file():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    try:
        current_content = doc_path.read_text(encoding="utf-8")
    except OSError:
        current_content = ""

    sidecar = _sidecar_path(doc_path)
    # Save original as sidecar if it doesn't exist yet so diff works
    if not sidecar.is_file() and current_content and current_content != body.content:
        try:
            sidecar.write_text(current_content, encoding="utf-8")
        except OSError:
            pass

    try:
        doc_path.write_text(body.content, encoding="utf-8")
    except OSError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to save document edits: {str(exc)}",
        ) from exc

    previous_content = None
    if sidecar.is_file():
        try:
            previous_content = sidecar.read_text(encoding="utf-8")
        except OSError:
            previous_content = None

    summary = _summary(doc_path, root)
    return GeneratedDocument(
        **summary.model_dump(),
        content=body.content,
        previous_content=previous_content,
    )



